# Generated by Django 4.2.10 on 2024-07-19 09:41

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211014_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
